Upgrade pax stable python version
GoogleCloudPlatform/ml-auto-solutions pull request #87
Opened 2024-01-25 17:53 UTC by gkroiz

# Description
The pax stable tests include optax as a dependency, which on 1/15 released a new stable version dependent on a newer python version. As a result, this PR updates the python version for the pax stable tests.

# Tests
Will include link once the tests are done

# Checklist
Before submitting this PR, please make sure (put X in square brackets):
- [X] I have performed a self-review of my code.
- [X] I have necessary comments in my code, particularly in hard-to-understand areas.
- [X] I have run one-shot tests and provided workload links above if applicable. 
- [X] I have made or will make corresponding changes to the doc if needed.

2024-01-26 02:32 UTC, RissyRan approved these changes

2024-01-26 02:33 UTC, RissyRan requested changes
Waiting for test link. Thanks!

2024-01-26 06:26 UTC, gkroiz commented
The fix to the stable tests might require a new pax version, in which case I will hold this PR off for the time being.

2024-02-21 09:13 UTC, gkroiz commented
> The fix to the stable tests might require a new pax version, in which case I will hold this PR off for the time being.

new pax/praxis 1.3.1 is released, will open this PR, ready for review/merge

2024-02-21 21:58 UTC, RissyRan commented on dags/solutions_team/configs/pax/solutionsteam_pax_supported_config.py
> +    if pax_version in [PaxVersion.STABLE, PaxVersion.NIGHTLY]:
Do you think it's reasonable to set `RuntimeVersion.TPU_UBUNTU2204_BASE.value` as default for rest of TPU versions? As it works for both stable and nightly

2024-02-23 21:21 UTC, RissyRan approved these changes

2024-02-23 21:22 UTC, merged